### ISSUE TITLE
Add more example handbooks

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/group-handbook-template#7]
There's a bunch of example lab handbooks in this thread: https://neuromatch.social/@elduvelle/112876144489195405.

Link to them in the README as sources of potential inspiration.

**Comment by Aariq** [comment]
Link to this repo: https://github.com/cct-datascience/open-lab-handbooks

**Comment by embruna** [comment]
The Weecology Lab at UF has an excellent one: [https://wiki.weecology.org/docs/](https://wiki.weecology.org/docs/)

**Comment by Aariq** [comment]
Thanks Emilio!  I'll add a link to this over here: https://github.com/cct-datascience/open-lab-handbooks
